package de.mprengemann.hwr.timetabel;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import de.mprengemann.hwr.timetabel.Subjects;
import de.mprengemann.hwr.timetabel.Events;

import de.mprengemann.hwr.timetabel.SubjectsDao;
import de.mprengemann.hwr.timetabel.EventsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig subjectsDaoConfig;
    private final DaoConfig eventsDaoConfig;

    private final SubjectsDao subjectsDao;
    private final EventsDao eventsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        subjectsDaoConfig = daoConfigMap.get(SubjectsDao.class).clone();
        subjectsDaoConfig.initIdentityScope(type);

        eventsDaoConfig = daoConfigMap.get(EventsDao.class).clone();
        eventsDaoConfig.initIdentityScope(type);

        subjectsDao = new SubjectsDao(subjectsDaoConfig, this);
        eventsDao = new EventsDao(eventsDaoConfig, this);

        registerDao(Subjects.class, subjectsDao);
        registerDao(Events.class, eventsDao);
    }
    
    public void clear() {
        subjectsDaoConfig.getIdentityScope().clear();
        eventsDaoConfig.getIdentityScope().clear();
    }

    public SubjectsDao getSubjectsDao() {
        return subjectsDao;
    }

    public EventsDao getEventsDao() {
        return eventsDao;
    }

}
